sonar.projectKey=Space2Study-UA-1355-02_Client-02
sonar.organization=space2study-ua-1355-02

sonar.projectName=Client-02

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.exclusions=**/src/tests/**/*, **/build-story/*
sonar.coverage.exclusions=**/src/constants/*, **/src/tests/**/*, **/*.styles.ts

sonar.tests=./src/tests

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude test subdirectories from source scope
sonar.javascript.lcov.reportPaths=./src/tests/coverage/lcov.info
sonar.testExecutionReportPaths=./test-report.xml