name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Node 18
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name : Npm Install
        run: npm install
        
     # - name : Lint
     #   run : npm run lint
        
      - name : Test
        run: npm test
        
     # Generate sonar-project.properties dynamically
      - name: Generate sonar-project.properties
        run: |
          echo "sonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}" > sonar-project.properties
          echo "sonar.organization=${{ secrets.SONAR_ORGANIZATION }}" >> sonar-project.properties
          echo "sonar.sources=." >> sonar-project.properties
          echo "sonar.exclusions=**/src/tests/**/*" >> sonar-project.properties
          echo "sonar.coverage.exclusions=**/src/tests/**/*" >> sonar-project.properties
          echo "sonar.tests=./src/tests" >> sonar-project.properties
          echo "sonar.sourceEncoding=UTF-8" >> sonar-project.properties
          # echo "sonar.javascript.lcov.reportPaths=./src/tests/coverage/lcov.info" >> sonar-project.properties
          # echo "sonar.testExecutionReportPaths=./test-report.xml" >> sonar-project.properties

      # Run SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 

      # Delete sonar-project.properties after scan
      - name: Remove sonar-project.properties
        if: always()
        run: rm sonar-project.properties
